### PR TITLE
rwxrob/1

### PR DESCRIPTION
**Pull request by rwxrob**
- Add Legal to README.md
- chore: remove defunct rresp.go file
- chore: remove prompt_test.go file
- chore: make configurable clusters easier to maintain
- chore: move OIDC auth into own pkg
- chore: move exec and prompt into new run pkg
- chore: drop go.work
- chore: drop go.work
- chore: add gitingore for go.work*
- feat: add kubeconf with Contexts
- chore: move conf file and dir to kubeconf
- chore: break out kubeconf variables into calls
- chore: cleanup  go.sum
- feat: use current context user

### CODE REVIEW

**Review by rwxrob — COMMENTED** [review]
Looks good.

**Review by GrayHatter — APPROVED** [review]
UNREAD 

LGTM

**Comment by nevzatseferoglu** [comment]
Looks good to me!

**Comment by mcdxwell** [comment]
Looks good 👍

**Pull request merged**
